spring:
  datasource:
    name: testDatasource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tenant_insert?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 111111

# 整合mybatis
mybatis:
  #  typeAliasesPackage: com.neuedu.entity
  mapper-locations: classpath*:com/test/demo/**/mapper/*.xml
logging:
  level:
    com.test.demo: debug